
eureka:
  client:
    register-with-eureka: false #不需要检测服务
    service-url:
            defaultZone: http://eureka8001.java.com:8001/eureka/,http://eureka8002.java.com:8002/eureka/,http://eureka8003.java.com:8003/eureka/
server:
  port: 7001
