server:
  port: 3001
  connection-timeout: 3000

# 数据源配置
spring:
  application:
    name: app-zuul



eureka:
  instance:
    instance-id: microservice-user-zuul:3001 #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
       #把服务注册到eureka注册中心  集群
      defaultZone: http://eureka8001.java.com:8001/eureka/,http://eureka8002.java.com:8002/eureka/,http://eureka8003.java.com:8003/eureka/

#路由规则配置： /user和app-user地址进行映射，默认去除前缀，即访问/app-user/user/findOne
#访问规则：zuul.java1234.com:3001/user/user/findOne
zuul:
  routes:
    user:
      path: /user/**
      serviceId: app-user

